apiVersion: v1
kind: Service
metadata:
  name: scaletestapp-service
spec:
  selector:
    app: scaletestapp  # Должно совпадать с метками Pod из Deployment
  ports:
    - protocol: TCP
      port: 80         # Порт, на котором Service принимает запросы
      targetPort: 8080 # Порт контейнера (как в Deployment)
  type: ClusterIP      # Тип Service (для внутреннего доступа)
